// TradeLab — Phase B: free public market data + paper trading + reusable backtest
// SIMULATION ONLY. Uses Binance public endpoints (no key). Not financial advice.
const https = require("https");
function getJson(url){return new Promise((res,rej)=>{https.get(url,{headers:{accept:"application/json"}},r=>{if(r.statusCode>=300&&r.headers.location)return getJson(r.headers.location).then(res,rej);let d="";r.on("data",c=>d+=c);r.on("end",()=>{try{res(JSON.parse(d));}catch(e){rej(e);}});}).on("error",rej).setTimeout(8000,function(){this.destroy(new Error("timeout"));});});}
async function candles(symbol){const s=encodeURIComponent(symbol||"BTCUSDT");const d=await getJson(`https://api.binance.com/api/v3/klines?symbol=${s}&interval=1h&limit=100`);if(!Array.isArray(d))throw new Error("bad klines");return d.map(k=>({t:k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],v:+k[5]}));}
function sma(a,n){if(a.length<n||n<=0)return null;return a.slice(-n).reduce((x,y)=>x+y,0)/n;}
function rsi(closes,period=14){if(closes.length<period+1)return null;let g=0,l=0;for(let i=closes.length-period-1;i<closes.length-1;i++){const d=closes[i+1]-closes[i];if(d>0)g+=d;else l-=d;}if(l===0)return 100;return 100-100/(1+g/l);}
function momentumSignal(cs){const closes=cs.map(x=>x.c);const f=sma(closes.slice(0,-1),12),sl=sma(closes.slice(0,-1),48),r=rsi(closes);if(f==null||sl==null)return{side:"flat",why:"insufficient-history"};const px=closes[closes.length-1];if(f>sl&&r!=null&&r<70)return{side:"long",entry:+px.toFixed(2),stop:+(px*0.985).toFixed(2),target:+(px*1.03).toFixed(2),ind:{sma12:+f.toFixed(2),sma48:+sl.toFixed(2),rsi:+r.toFixed(1)},why:"SMA12>SMA48 and RSI<70"};return{side:"flat",why:f<=sl?"SMA12<=SMA48":"RSI>=70",ind:{sma12:+f.toFixed(2),sma48:+sl.toFixed(2),rsi:r!=null?+r.toFixed(1):null}};}
function meanRevSignal(cs){const closes=cs.map(x=>x.c);if(closes.length<51)return{side:"flat",why:"insufficient-history"};const last=closes[closes.length-1],m=sma(closes,50);const sd=Math.sqrt(closes.slice(-50).reduce((a,v)=>a+(v-m)**2,0)/50);if(sd===0)return{side:"flat",why:"zero-sigma"};const z=(last-m)/sd;const ind={z:+z.toFixed(2),sma50:+m.toFixed(2)};if(z<-1.5)return{side:"long",entry:+last.toFixed(2),stop:+(last*0.99).toFixed(2),target:+m.toFixed(2),ind,why:`${z.toFixed(2)} sigma below mean`};if(z>1.5)return{side:"short",entry:+last.toFixed(2),stop:+(last*1.01).toFixed(2),target:+m.toFixed(2),ind,why:`${z.toFixed(2)} sigma above mean`};return{side:"flat",why:`abs(z)=${Math.abs(z).toFixed(2)} < 1.5`,ind};}
async function signal(kind,symbol){const cs=await candles(symbol);const s=(kind==="meanrev"?meanRevSignal:momentumSignal)(cs);return Object.assign({kind,symbol:(symbol||"BTCUSDT").toUpperCase(),ts:Date.now(),bars:cs.length},s);}
function backtest(cs,strat,opts){const feeBps=(opts&&opts.feeBps)!=null?opts.feeBps:10;const trades=[];let pos=null;
for(let i=55;i<cs.length;i++){const win=cs.slice(0,i+1);const sig=strat(win);
 if(!pos&&sig.side&&sig.side!=="flat"){pos={side:sig.side,entry:sig.entry!=null?sig.entry:win[i].c,stop:sig.stop,target:sig.target,t:i};}
 else if(pos){const bar=win[i];const hitStop=pos.side==="long"?bar.l<=pos.stop:bar.h>=pos.stop;const hitTgt=pos.side==="long"?bar.h>=pos.target:bar.l<=pos.target;
  if(hitStop||hitTgt){const exit=hitStop?pos.stop:pos.target;const grossPct=pos.side==="long"?(exit-pos.entry)/pos.entry:(pos.entry-exit)/pos.entry;const net=grossPct-(feeBps/10000)*2;
   trades.push({openedAtBar:pos.t,closedAtBar:i,side:pos.side,entry:+(+pos.entry).toFixed(2),exit:+(+exit).toFixed(2),netPct:+(net*100).toFixed(3),result:net>0?"win":"loss"});pos=null;}}}
const wins=trades.filter(t=>t.netPct>0).length;const tot=trades.reduce((a,t)=>a+t.netPct,0);
return{n:trades.length,wins,winRate:trades.length?+(wins/trades.length*100).toFixed(1):0,avgNetPct:trades.length?+(tot/trades.length).toFixed(3):0,totalNetPct:+tot.toFixed(3),feeModel:`${feeBps}bps x2`,disclaimer:"SIMULATION ONLY - historical bars - NOT financial advice",trades};}
module.exports={getJson,candles,sma,rsi,momentumSignal,meanRevSignal,signal,backtest};
